const sampleListings = [
  {
    title: "UltraTech 53 Grade PPC Cement (50 Bags)",
    description:
      "Surplus fresh stock from a high-rise residential project in Andheri. All 50 bags are completely sealed, stored in a dry weatherproof container, manufactured within the last 30 days. Perfect for slab and foundation casting.",
    category: "Cement",
    condition: "Brand New / Surplus",
    quantity: 50,
    unit: "Bags",
    price: 330,
    originalPrice: 420,
    location: "Andheri East, Mumbai",
    country: "India",
    contactPhone: "+91 98201 12345",
    contactEmail: "surplus.materials@mumbaibuilders.com",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=1000&q=80",
    },
  },
  {
    title: "Tata Tiscon 500D Fe TMT Steel Rebars 12mm & 16mm",
    description:
      "Approx. 2.2 tonnes of leftover Tata Tiscon certified TMT steel rebars (bundled into 12mm and 16mm full standard 12-meter lengths). Zero rust, factory tagged, ready for direct dispatch.",
    category: "Steel & Iron",
    condition: "Brand New / Surplus",
    quantity: 2,
    unit: "Tonnes",
    price: 54000,
    originalPrice: 68000,
    location: "Whitefield, Bengaluru",
    country: "India",
    contactPhone: "+91 97401 56789",
    contactEmail: "structures@infraprojects.in",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1000&q=80",
    },
  },
  {
    title: "First-Class Kiln-Fired Red Clay Bricks (3000 Pcs)",
    description:
      "Standard size first-class red clay bricks left over from a villa perimeter wall construction. High compressive strength, sharp edges, undamaged and stacked neatly on wooden pallets for easy crane/truck loading.",
    category: "Bricks & Blocks",
    condition: "Brand New / Surplus",
    quantity: 3000,
    unit: "Pieces",
    price: 8,
    originalPrice: 12,
    location: "Sector 62, Noida",
    country: "India",
    contactPhone: "+91 98110 87654",
    contactEmail: "noidavillas@gmail.com",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1590069261209-f8e9b8642343?auto=format&fit=crop&w=1000&q=80",
    },
  },
  {
    title: "Kajaria 600x1200mm Glazed Vitrified Floor Tiles (40 Boxes)",
    description:
      "Premium statuario marble-finish vitrified floor tiles by Kajaria. 40 unopened original boxes (approx. 620 sq. ft. coverage). Unused excess order from a luxury duplex renovation.",
    category: "Tiles & Marble",
    condition: "Brand New / Surplus",
    quantity: 620,
    unit: "Sq. Ft.",
    price: 52,
    originalPrice: 85,
    location: "Banjara Hills, Hyderabad",
    country: "India",
    contactPhone: "+91 99890 23456",
    contactEmail: "hyd.interiors@outlook.com",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1000&q=80",
    },
  },
  {
    title: "Heavy Duty CPVC Schedule 80 Plumbing Pipes & Fittings Lot",
    description:
      "Over 120 meters of Supreme CPVC hot/cold water pipes (1-inch & 1.5-inch diameter) along with 45+ brass elbows, tees, and ball valves. Remaining inventory after hospital plumbing overhaul.",
    category: "Pipes & Plumbing",
    condition: "Like New / Unused",
    quantity: 120,
    unit: "Meters",
    price: 180,
    originalPrice: 275,
    location: "Kothrud, Pune",
    country: "India",
    contactPhone: "+91 98220 99887",
    contactEmail: "puneplumb@yahoo.com",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?auto=format&fit=crop&w=1000&q=80",
    },
  },
  {
    title: "Handcrafted Solid CP Teak Wood Door Frames (4 Units)",
    description:
      "Seasoned Central Province (CP) solid teak wood door frames with routed rebate and sanded finish. Dimensions: 7ft x 3.5ft x 5in. Surplus custom millwork from luxury bungalow construction.",
    category: "Doors & Windows",
    condition: "Brand New / Surplus",
    quantity: 4,
    unit: "Pieces",
    price: 4800,
    originalPrice: 8500,
    location: "Thaltej, Ahmedabad",
    country: "India",
    contactPhone: "+91 98790 44332",
    contactEmail: "ahmedabadmillwork@gmail.com",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80",
    },
  },
  {
    title: "Asian Paints Apex Ultima Exterior Emulsion White (4 x 20L)",
    description:
      "4 unopened sealed 20-litre buckets of Asian Paints Apex Ultima exterior weather-proof emulsion in Brilliant White. High UV resistance and 7-year performance warranty. Manufactured 2 months ago.",
    category: "Paints & Finishes",
    condition: "Brand New / Surplus",
    quantity: 80,
    unit: "Liters",
    price: 240,
    originalPrice: 360,
    location: "Anna Nagar, Chennai",
    country: "India",
    contactPhone: "+91 94440 12890",
    contactEmail: "chennaipainters@gmail.com",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=1000&q=80",
    },
  },
  {
    title: "Schneider Electric Modular Switches, Dimmers & Plates Kit",
    description:
      "Lot of 75 Schneider Electric Zencelo switches, 20 universal sockets, and 12 glass-finish modular faceplates in charcoal grey. Brand new sealed boxes from modern commercial fit-out.",
    category: "Electrical",
    condition: "Brand New / Surplus",
    quantity: 75,
    unit: "Pieces",
    price: 110,
    originalPrice: 195,
    location: "Gurugram, Haryana",
    country: "India",
    contactPhone: "+91 99100 88776",
    contactEmail: "delhincr.electricals@gmail.com",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1000&q=80",
    },
  },
  {
    title: "Greenply 19mm Marine Grade Waterproof Plywood (15 Sheets)",
    description:
      "IS:710 certified Greenply 19mm BWP (Boiling Water Proof) marine plywood full 8ft x 4ft sheets. Calibrated core, borer and termite proof. Ideal for modular kitchens and bathroom vanities.",
    category: "Wood & Timber",
    condition: "Brand New / Surplus",
    quantity: 15,
    unit: "Pieces",
    price: 2100,
    originalPrice: 3200,
    location: "Salt Lake, Kolkata",
    country: "India",
    contactPhone: "+91 98300 77665",
    contactEmail: "kolkatawoodworks@gmail.com",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1000&q=80",
    },
  },
  {
    title: "Italian Botticino Marble Slabs & Polished Cut Pieces",
    description:
      "Salvaged unused slabs and cut-to-size pieces of authentic Italian Botticino Beige marble (18mm thickness). High polish, fine grain, approx. 180 sq. ft. total. Excellent for fireplace surrounds, vanity tops, or accent flooring.",
    category: "Tiles & Marble",
    condition: "Gently Used / Salvaged",
    quantity: 180,
    unit: "Sq. Ft.",
    price: 140,
    originalPrice: 280,
    location: "Indiranagar, Bengaluru",
    country: "India",
    contactPhone: "+91 98450 33445",
    contactEmail: "stoneworks.bangalore@gmail.com",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80",
    },
  },
  {
    title: "Aluminum 3-Track Sliding Windows with Mosquito Mesh (5 Units)",
    description:
      "Jindal heavy aluminum powder-coated anodized bronze finish 3-track sliding window frames with 5mm toughened Saint-Gobain clear glass and SS-304 insect mesh. Standard size: 5ft (W) x 4ft (H).",
    category: "Doors & Windows",
    condition: "Like New / Unused",
    quantity: 5,
    unit: "Units",
    price: 3800,
    originalPrice: 6200,
    location: "Vashi, Navi Mumbai",
    country: "India",
    contactPhone: "+91 98200 44556",
    contactEmail: "navimumbaiglazing@gmail.com",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=1000&q=80",
    },
  },
  {
    title: "AAC Lightweight Concrete Autoclaved Blocks (400 Blocks)",
    description:
      "Eco-friendly, thermal insulating AAC blocks (size: 600mm x 200mm x 150mm). Leftover order from green building certified commercial warehouse construction. Dry stacked.",
    category: "Bricks & Blocks",
    condition: "Brand New / Surplus",
    quantity: 400,
    unit: "Pieces",
    price: 55,
    originalPrice: 85,
    location: "Sector 48, Gurgaon",
    country: "India",
    contactPhone: "+91 98100 66778",
    contactEmail: "greenbuilder.ncr@gmail.com",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1590069261209-f8e9b8642343?auto=format&fit=crop&w=1000&q=80",
    },
  },
];

module.exports = { data: sampleListings };