const sampleListings = [
  {
    title: "JK Super PPC Cement Full Pallet Lot (80 Bags / 4 Tonnes)",
    description:
      "Surplus batch of 80 unopened 50kg bags of JK Super Portland Pozzolana Cement (PPC). Stored indoors on treated wooden pallets in a temperature-controlled dry warehouse. Manufactured within the past 20 days with zero moisture exposure or lump formation. Excellent workability and sulphate resistance for structural RCC casting, brickwork, and plastering.",
    category: "Cement",
    condition: "Brand New / Surplus",
    quantity: 80,
    unit: "Bags",
    price: 325,
    originalPrice: 420,
    location: "Sanand GIDC Warehouse, Ahmedabad",
    country: "India",
    contactPhone: "+91 98790 11223",
    contactEmail: "surplus.ahmedabadcement@gmail.com",
    image: {
      filename: "jk_cement_warehouse_pallets",
      url: "https://www.jkcement.com/wp-content/uploads/2024/05/cement-bags-are-placed-pallets-stored-warehouses-cement-bags-construction-scaled.jpg",
    },
  },
  {
    title: "Ambuja Kawach Water-Shield Concrete Cement (45 Bags)",
    description:
      "Leftover order of Ambuja Kawach water-repellent specially formulated cement with active silane technology for preventing dampness and efflorescence. 45 fresh 50kg bags stored in tamper-proof HDPE woven bags. Surplus from a podium waterproofing project.",
    category: "Cement",
    condition: "Brand New / Surplus",
    quantity: 45,
    unit: "Bags",
    price: 340,
    originalPrice: 445,
    location: "Hinjewadi Phase 3, Pune",
    country: "India",
    contactPhone: "+91 98220 55667",
    contactEmail: "pune.contractors@gmail.com",
    image: {
      filename: "ambuja_cement_bags",
      url: "https://4.imimg.com/data4/PF/XQ/MY-22275017/cement-bags.jpg",
    },
  },
  {
    title: "UltraTech Super 53 Grade High-Strength OPC Cement (60 Bags)",
    description:
      "Unopened 50kg bags of UltraTech 53 Grade Ordinary Portland Cement. Delivers high early compressive strength for RCC columns, beams, heavy precast elements, and slab casting. Tested batch, stored under heavy tarpaulin covers on timber skids.",
    category: "Cement",
    condition: "Brand New / Surplus",
    quantity: 60,
    unit: "Bags",
    price: 335,
    originalPrice: 430,
    location: "Whitefield Outer Ring Road, Bengaluru",
    country: "India",
    contactPhone: "+91 97401 88990",
    contactEmail: "blr.ultratech.surplus@gmail.com",
    image: {
      filename: "ultratech_cement_bag",
      url: "https://images.jdmagicbox.com/quickquotes/images_main/ultratech-cement-bag-2221396535-b477xvul.jpg",
    },
  },
  {
    title: "ACC Concrete+ High-Performance 53 Grade Cement (35 Bags)",
    description:
      "35 bags of fresh ACC Concrete+ engineered cement with micro-silica technology for denser concrete matrix and low heat of hydration. Perfect for residential foundation, plastering, and masonry work.",
    category: "Cement",
    condition: "Brand New / Surplus",
    quantity: 35,
    unit: "Bags",
    price: 330,
    originalPrice: 425,
    location: "Sector 62, Noida",
    country: "India",
    contactPhone: "+91 98110 33445",
    contactEmail: "noidabuilders.materials@gmail.com",
    image: {
      filename: "acc_cement_bag",
      url: "https://tiimg.tistatic.com/fp/1/009/506/cement-bag-477.jpg",
    },
  },
  {
    title: "Birla White Wall Care & Decorative Portland White Cement (50 Bags)",
    description:
      "Unopened 50kg bags of genuine Birla White Portland Cement. High whiteness index (>89% Hunter scale), superior compressive strength, and uniform fineness. Surplus stock from luxury architectural terrazzo and wall-care plastering contract. Stored indoors on plastic pallets.",
    category: "Cement",
    condition: "Brand New / Surplus",
    quantity: 50,
    unit: "Bags",
    price: 410,
    originalPrice: 540,
    location: "GIDC Makarpura, Vadodara",
    country: "India",
    contactPhone: "+91 98980 11445",
    contactEmail: "surplus.vadodaracement@gmail.com",
    image: {
      filename: "birla_white_cement_stack",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNg7H4bTH6QBjQx2Ai2FkL9xvrUT2i0H_1RnGqbHY17qdvvDGyDFmO2Rhi&s=10",
    },
  },
  {
    title: "High-Grade 53 OPC Construction Cement Paper Sacks Lot (70 Bags)",
    description:
      "Surplus lot of 70 multi-ply moisture-barrier kraft paper sacks of Grade 53 Ordinary Portland Cement (OPC). High early-setting strength for rapid slab curing and load-bearing columns. All bags sealed and undamaged.",
    category: "Cement",
    condition: "Brand New / Surplus",
    quantity: 70,
    unit: "Bags",
    price: 320,
    originalPrice: 415,
    location: "Peenya Industrial Area, Bengaluru",
    country: "India",
    contactPhone: "+91 97401 66778",
    contactEmail: "blr.cementsurplus@gmail.com",
    image: {
      filename: "cement_paper_sacks_stack",
      url: "https://media.istockphoto.com/id/804350724/photo/cement-bags-stack-paper-sacks-isolated-on-white-background-3d-illustration.jpg?s=612x612&w=0&k=20&c=aIm_kuOyK_pTENn5oXp03wyfAmRz1ifc21cPm87ll2A=",
    },
  },
  {
    title: "Dalmia DSP High-Performance Weather-Resistant Duralife Cement (40 Bags)",
    description:
      "40 unopened bags of Dalmia DSP specialty engineered slag cement. High resistance against chloride and sulphate attack, low heat of hydration, and micro-pore filling technology for damp-proof structural concrete.",
    category: "Cement",
    condition: "Brand New / Surplus",
    quantity: 40,
    unit: "Bags",
    price: 345,
    originalPrice: 450,
    location: "Sector 62, Noida",
    country: "India",
    contactPhone: "+91 98110 99887",
    contactEmail: "ncr.dalmiacements@gmail.com",
    image: {
      filename: "dalmia_dsp_cement_bag",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6rnl_UjHLjrFoUmnukkk7hmC0pTyGRIr3IGD6IyDcoA&s=10",
    },
  },
  {
    title: "Bangur Power High-Strength Premium PPC Cement (55 Bags)",
    description:
      "55 fresh sealed bags of Bangur Power Portland Pozzolana Cement manufactured with heavy-duty clinker and fly ash blend. Stored under tarpaulin on elevated wooden skids. Ideal for foundation, brick masonry, and high-durability plastering.",
    category: "Cement",
    condition: "Brand New / Surplus",
    quantity: 55,
    unit: "Bags",
    price: 330,
    originalPrice: 430,
    location: "Hinjewadi Phase 1, Pune",
    country: "India",
    contactPhone: "+91 98220 88776",
    contactEmail: "pune.bangurcement@gmail.com",
    image: {
      filename: "bangur_power_cement_bag",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTF3TqmYV8uG_GGlAKocqlu6LZpKR5v06z15__IiimM29hfLPayTcocylg-&s=10",
    },
  },
  {
    title: "Fe 500D Grade 10mm TMT Steel Rebar Bundles (1.5 Tonnes)",
    description:
      "Surplus factory strapped bundles of 10mm Fe 500D high-ductility TMT rebars (standard 12m lengths). Leftover order from a rooftop solar mounting structure and boundary wall foundation. High earthquake and corrosion resistance with zero rust.",
    category: "Steel & Iron",
    condition: "Brand New / Surplus",
    quantity: 2,
    unit: "Tonnes",
    price: 52000,
    originalPrice: 66000,
    location: "Sanand Industrial Corridor, Ahmedabad",
    country: "India",
    contactPhone: "+91 98790 44556",
    contactEmail: "solar.steelsurplus@gmail.com",
    image: {
      filename: "tmt_steel_rebars_10mm",
      url: "https://5.imimg.com/data5/SELLER/Default/2024/6/428760077/SY/OB/NC/155778369/10mm-solar-iron-tmt-bar-500x500.jpg",
    },
  },
  {
    title: "Heavy Cylindrical MS Structural Hollow Steel Pipes (100mm / 4-Inch)",
    description:
      "Seamless round mild steel (MS) structural hollow pipes (Schedule 40, 100mm outer diameter, 4.5mm wall thickness). Primer coated against atmospheric corrosion. Suitable for shed structural columns, heavy trusses, signposts, and industrial framing.",
    category: "Steel & Iron",
    condition: "Brand New / Surplus",
    quantity: 24,
    unit: "Pieces",
    price: 1850,
    originalPrice: 2900,
    location: "Manesar Industrial Area, Gurugram",
    country: "India",
    contactPhone: "+91 99100 44332",
    contactEmail: "ncr.steelpipes@infra.com",
    image: {
      filename: "cylindrical_steel_pipe",
      url: "https://www.jkcement.com/wp-content/uploads/2024/10/cylindrical-steel-pipe-1024x724.jpg",
    },
  },
  {
    title: "Heavy Structural Steel Columns & Pre-Engineered Truss Sections Lot",
    description:
      "Surplus structural steel components including pre-welded base-plated columns, angle iron bracing, and roof trusses leftover from warehouse shed expansion. Red oxide anti-rust primed, bolt-hole pre-drilled for fast erection.",
    category: "Steel & Iron",
    condition: "Like New / Unused",
    quantity: 4,
    unit: "Tonnes",
    price: 48000,
    originalPrice: 72000,
    location: "Ambattur Industrial Estate, Chennai",
    country: "India",
    contactPhone: "+91 94440 88776",
    contactEmail: "chennai.steelstructures@gmail.com",
    image: {
      filename: "structural_steel_construction",
      url: "https://5.imimg.com/data5/SELLER/Default/2024/10/455929881/MY/EU/KU/995004/structural-steel-construction.jpg",
    },
  },
  {
    title: "High-Precision MS Steel Hollow Tubular Sections (50mm / 2-Inch)",
    description:
      "Cold-rolled precision mild steel hollow tubes (50mm outer diameter, 2.5mm wall thickness). Clean mill finish with protective oil coating. Perfect for staircase railings, gates, furniture fabrication, and mezzanine supports.",
    category: "Steel & Iron",
    condition: "Brand New / Surplus",
    quantity: 40,
    unit: "Pieces",
    price: 650,
    originalPrice: 1050,
    location: "Bhosari MIDC, Pune",
    country: "India",
    contactPhone: "+91 98220 33221",
    contactEmail: "pune.metaltubes@gmail.com",
    image: {
      filename: "steel_metal_tubes",
      url: "https://img.magnific.com/premium-photo/steel-metal-tubes_241146-775.jpg?semt=ais_hybrid&w=740&q=80",
    },
  },
  {
    title: "Universal Structural Heavy Steel I-Beams (ISMB 250 / 12m Lengths)",
    description:
      "SAIL certified heavy-gauge hot-rolled structural steel I-Beams (ISMB 250, weight ~37.3 kg/m, full 12-meter straight lengths). Stored in dry steel yard with zero camber/twist. Ideal for primary bridge girders, overhead crane runways, and heavy multi-story floor supports.",
    category: "Steel & Iron",
    condition: "Brand New / Surplus",
    quantity: 8,
    unit: "Pieces",
    price: 9200,
    originalPrice: 14500,
    location: "Durgapur Steel City Hub, Kolkata",
    country: "India",
    contactPhone: "+91 98300 55443",
    contactEmail: "durgapur.heavybeams@gmail.com",
    image: {
      filename: "steel_beams_structural",
      url: "https://img.magnific.com/premium-vector/steel-beams-isolated-white-background_876236-3363.jpg?semt=ais_hybrid&w=740&q=80",
    },
  },
  {
    title: "Heavy Ribbed Fe 550D Construction Iron Rods & Rebars (16mm & 20mm)",
    description:
      "Surplus heavy-grade 16mm and 20mm high-yield ribbed steel reinforcement bars. High bond strength rib pattern, tested and certified for heavy building foundations, deep pile caps, and bridge piers. Neatly bundled and tagged.",
    category: "Steel & Iron",
    condition: "Brand New / Surplus",
    quantity: 3,
    unit: "Tonnes",
    price: 53500,
    originalPrice: 69000,
    location: "Peenya Industrial Area, Bengaluru",
    country: "India",
    contactPhone: "+91 97401 66554",
    contactEmail: "blr.foundationsteels@gmail.com",
    image: {
      filename: "ribbed_iron_rods",
      url: "https://5.imimg.com/data5/SELLER/Default/2023/10/357006251/FQ/US/MS/23315060/iron-rods.png",
    },
  },
  {
    title: "Heavy Galvanized & Black Annealed Steel Binding Wire Coils (25kg x 20 Rolls)",
    description:
      "Surplus inventory of 20 unopened 25kg rolls (approx. 500kg total) of 18-gauge (1.2mm) high-ductility annealed steel and GI binding wire. Uniform tensile strength, flexible for fast rebar tying, zero knotting breakage, and anti-corrosive oil coated. Stored in dry warehouse.",
    category: "Steel & Iron",
    condition: "Brand New / Surplus",
    quantity: 20,
    unit: "Pieces",
    price: 1450,
    originalPrice: 2100,
    location: "Manesar Industrial Area, Gurugram",
    country: "India",
    contactPhone: "+91 99100 88221",
    contactEmail: "gurugram.wirecoils@gmail.com",
    image: {
      filename: "binding_wire_coils",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRH1HxG9clGeklVqxewFjGUxZDcuzbrwDCu7q1vnZOp4KmkTS5JdQQEFrLi&s=10",
    },
  },
  {
    title: "HRB500 / Grade 60 High-Yield Corrugated Deformed Steel Rebars (2.5 Tonnes)",
    description:
      "Certified high-yield Grade 60 / HRB500 hot-rolled corrugated deformed steel rebars (assorted standard 12m bundles in 12mm, 16mm, and 20mm diameters). Superior elongation (>16%) and ultimate tensile strength for seismic-resistant multi-story framing, flyover piers, and heavy raft foundations. Mill test certificates available.",
    category: "Steel & Iron",
    condition: "Brand New / Surplus",
    quantity: 3,
    unit: "Tonnes",
    price: 51000,
    originalPrice: 67000,
    location: "Sanand GIDC Steel Yard, Ahmedabad",
    country: "India",
    contactPhone: "+91 98790 77334",
    contactEmail: "ahmedabad.rebardealers@gmail.com",
    image: {
      filename: "corrugated_steel_rebar_rods",
      url: "https://image.made-in-china.com/202f0j00iygoBlCrrKuv/Grade-40-and-Grade-60-HRB500-Steel-Couurgated-Iron-Rod-6m-5-8-1-2-3-4inch-Round-Steel-Rebar-Approx-Iron-Rods-Bar-for-Bridge-Construction-From-Factory.webp",
    },
  },
  {
    title: "Heavy MS Structural Equal L-Angles (50x50x6mm & 75x75x6mm / 30 Pieces)",
    description:
      "Heavy structural mild steel equal angle iron sections (standard 6-meter lengths in 50x50x6mm and 75x75x6mm). Surplus stock from an industrial PEB warehouse truss and solar ground-mount racking contract. Straight cut ends, zero twist, painted with protective red oxide primer.",
    category: "Steel & Iron",
    condition: "Brand New / Surplus",
    quantity: 30,
    unit: "Pieces",
    price: 1150,
    originalPrice: 1750,
    location: "Bhosari MIDC, Pune",
    country: "India",
    contactPhone: "+91 98220 66112",
    contactEmail: "pune.anglemetals@gmail.com",
    image: {
      filename: "ms_equal_l_angles",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRI95yWlma9NcObx_3DN30UHZ2l9fpq9bHExz6g7fMcWYhHj3DnnVzE11A&s=10",
    },
  },
  {
    title: "High-Tensile Welded Wire Reinforcement Steel Mesh Mats (8x4 Ft / 25 Sheets)",
    description:
      "Heavy-duty 8ft x 4ft welded wire reinforcement fabric (BRC mesh, 6mm main wire with 150mm x 150mm grid spacing). Leftover from factory concrete flooring and retaining wall shotcreting project. Provides crack resistance and uniform load distribution for concrete floor slabs, driveways, and precast panels.",
    category: "Steel & Iron",
    condition: "Brand New / Surplus",
    quantity: 25,
    unit: "Pieces",
    price: 850,
    originalPrice: 1350,
    location: "Ambattur Industrial Area, Chennai",
    country: "India",
    contactPhone: "+91 94440 99332",
    contactEmail: "chennai.steelmesh@gmail.com",
    image: {
      filename: "welded_wire_steel_mesh_mat",
      url: "https://res.cloudinary.com/jerrick/image/upload/d_642250b563292b35f27461a7.png,f_jpg,fl_progressive,q_auto,w_1024/67567880305e68001d2565ea.png",
    },
  },
  {
    title: "First-Class Kiln-Fired Red Clay Building Bricks (3,500 Pcs)",
    description:
      "Surplus batch of 3,500 standard-size (9\" x 4.25\" x 2.75\") first-class wire-cut kiln-fired red clay bricks. Leftover from a boundary wall and multi-villa project. High compressive strength, uniform terracotta red colour, sharp edges, and zero breakage. Stacked neatly on pallets for easy crane or truck loading.",
    category: "Bricks & Blocks",
    condition: "Brand New / Surplus",
    quantity: 3500,
    unit: "Pieces",
    price: 7.5,
    originalPrice: 11.5,
    location: "Sector 62, Noida",
    country: "India",
    contactPhone: "+91 98110 87654",
    contactEmail: "noidabricksupply@gmail.com",
    image: {
      filename: "red_clay_bricks",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMOpYXgECgp13xa-cUGXukhzhF_n6SSZ_weUji4k67vA&s=10",
    },
  },
  {
    title: "Eco-Friendly Fly Ash Solid Cement Masonry Bricks (2,000 Pcs)",
    description:
      "High-strength automated hydraulic pressed fly-ash cement bricks (size: 230mm x 110mm x 75mm). Smooth surface requiring 30% less plaster mortar. Leftover from a commercial park perimeter construction. Uniform shape and water absorption under 10%.",
    category: "Bricks & Blocks",
    condition: "Brand New / Surplus",
    quantity: 2000,
    unit: "Pieces",
    price: 5.5,
    originalPrice: 8.5,
    location: "Whitefield Industrial Area, Bengaluru",
    country: "India",
    contactPhone: "+91 97401 33445",
    contactEmail: "blr.ecobricks@gmail.com",
    image: {
      filename: "fly_ash_cement_bricks",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdMjBX4yMmcZU0TgcxrhuXUP9_JONXze_JeHG3jFCutQ&s=10",
    },
  },
  {
    title: "Solid Concrete Masonry & Clay Composite Bricks Lot (1,200 Pcs)",
    description:
      "Dense concrete and kiln-fired masonry composite bricks for load-bearing partition walls and foundation courses. High load-bearing capacity with excellent acoustic and thermal mass insulation. Dry-stored on pallets.",
    category: "Bricks & Blocks",
    condition: "Brand New / Surplus",
    quantity: 1200,
    unit: "Pieces",
    price: 9,
    originalPrice: 14,
    location: "Hinjewadi Phase 2, Pune",
    country: "India",
    contactPhone: "+91 98220 66778",
    contactEmail: "pune.compositebricks@gmail.com",
    image: {
      filename: "cement_and_clay_brick",
      url: "https://images.jdmagicbox.com/quickquotes/images_main/cement-and-clay-brick-2187663260-1st2jzkh.jpg",
    },
  },
  {
    title: "Pioneer Splendor Country Cream Terracotta Exposed Wall Cladding Bricks (800 Sq. Ft.)",
    description:
      "Premium architectural exposed facade brick tiles by Pioneer Bricks (Splendor series - Country Cream rustic finish). Unused remaining order from a luxury villa exterior cladding project. Weatherproof, natural clay texture, and zero maintenance.",
    category: "Bricks & Blocks",
    condition: "Brand New / Surplus",
    quantity: 800,
    unit: "Sq. Ft.",
    price: 45,
    originalPrice: 78,
    location: "Banjara Hills, Hyderabad",
    country: "India",
    contactPhone: "+91 99890 55443",
    contactEmail: "hyd.facadedesign@gmail.com",
    image: {
      filename: "pioneer_cladding_brick",
      url: "https://www.pioneerbricks.com/wp-content/uploads/product/splendor/country-cream/SPL-CC-01-cladding-brickwork-splendor-country-cream.jpg",
    },
  },
  {
    title: "Moroccan Encaustic Geometric Patterned Ceramic Accent Tiles (350 Sq. Ft.)",
    description:
      "Surplus lot of 200x200mm (8\" x 8\") vintage Moroccan decorative patterned matte ceramic tiles. Unopened factory boxes (approx. 22 boxes = 350 sq. ft.). Anti-skid R9 rating, ideal for cafe flooring, kitchen backsplashes, bathroom accent walls, and patio verandas.",
    category: "Tiles & Marble",
    condition: "Brand New / Surplus",
    quantity: 350,
    unit: "Sq. Ft.",
    price: 42,
    originalPrice: 75,
    location: "Indiranagar 100ft Road, Bengaluru",
    country: "India",
    contactPhone: "+91 97401 99887",
    contactEmail: "blr.boutiquetiles@gmail.com",
    image: {
      filename: "moroccan_pattern_tiles",
      url: "https://cadasbuilt.com/cdn/shop/files/CAB_PNG_SeamlessPatterns_0310.jpg?v=1723973026&width=1406",
    },
  },
  {
    title: "Classic Black & White Monochromatic Checkered Vitrified Floor Tiles (600x600mm)",
    description:
      "High-gloss double-charge vitrified tiles in timeless jet black and pure snow white (600mm x 600mm / 2ft x 2ft). 30 unopened boxes left over from a boutique restaurant fit-out. Super mirror polish, zero porosity, high abrasion resistance.",
    category: "Tiles & Marble",
    condition: "Brand New / Surplus",
    quantity: 480,
    unit: "Sq. Ft.",
    price: 40,
    originalPrice: 68,
    location: "Bandra West, Mumbai",
    country: "India",
    contactPhone: "+91 98200 88990",
    contactEmail: "mumbai.interiortiles@gmail.com",
    image: {
      filename: "checkered_vitrified_tiles",
      url: "https://c8.alamy.com/comp/G0GD4F/checkered-flooring-G0GD4F.jpg",
    },
  },
  {
    title: "Kajaria 600x1200mm Polished Glazed Vitrified Floor Tiles (Statuario White)",
    description:
      "Premium Statuario Italian marble-finish glazed vitrified large format floor tiles (600mm x 1200mm). 40 unopened original cartons (approx. 620 sq. ft. coverage). Remaining surplus from a luxury penthouse project. Mirror glaze nano-sealed surface.",
    category: "Tiles & Marble",
    condition: "Brand New / Surplus",
    quantity: 620,
    unit: "Sq. Ft.",
    price: 52,
    originalPrice: 85,
    location: "Banjara Hills, Hyderabad",
    country: "India",
    contactPhone: "+91 99890 23456",
    contactEmail: "hyd.interiors@outlook.com",
    image: {
      filename: "kajaria_pgvt_tiles",
      url: "https://images.jdmagicbox.com/quickquotes/images_main/-2luhjhr2.jpg",
    },
  },
  {
    title: "Multi-Texture Rustic Ceramic Floor & Bathroom Wall Tiles Assortment Lot (500 Sq. Ft.)",
    description:
      "Assorted lot of square 300x300mm and 300x600mm ceramic floor and wall tiles with rustic stone, warm terracotta, and textured wood finishes. Sealed boxes from builder display showroom clearance. Ideal for rental apartments, terrace tiling, or utility areas.",
    category: "Tiles & Marble",
    condition: "Brand New / Surplus",
    quantity: 500,
    unit: "Sq. Ft.",
    price: 32,
    originalPrice: 58,
    location: "Sector 48, Gurugram",
    country: "India",
    contactPhone: "+91 99100 77665",
    contactEmail: "ncr.tilesurplus@gmail.com",
    image: {
      filename: "multi_texture_tiles_lot",
      url: "https://img.magnific.com/free-vector/realistic-ceramic-floor-tiles-samples-composition-with-bunch-square-faced-tile-patterns-with-different-textures_1284-31833.jpg",
    },
  },
  {
    title: "Rigid Grey PVC Electrical Conduit & Plumbing Pipes Lot (25mm / 32mm)",
    description:
      "Surplus from a multi-story commercial wiring and grey-water plumbing contract. Heavy-duty unplasticized PVC (uPVC) rigid electrical conduit and casing pipes (25mm & 32mm outer diameter). Stored indoors on wooden warehouse pallet racks. Smooth inner bore, high impact resistance, zero crack or sun-damage. Ideal for concealed concrete slab electrical routing or exposed building pipework.",
    category: "Pipes & Plumbing",
    condition: "Brand New / Surplus",
    quantity: 220,
    unit: "Meters",
    price: 45,
    originalPrice: 80,
    location: "Kothrud Industrial Area, Pune",
    country: "India",
    contactPhone: "+91 98220 77889",
    contactEmail: "surplus.puneplumb@gmail.com",
    image: {
      filename: "pvc_grey_conduit_pipes",
      url: "https://res.cloudinary.com/d6s3l2i7/image/upload/v1787637523/rebuildx_materials/pvc_grey_conduit_pipes.jpg",
    },
  },
  {
    title: "Nikolas Complete UPVC & CPVC Pipes, Drainage SWR & Brass Valve Fitting Kit",
    description:
      "Complete assorted surplus lot of certified Nikolas Pipes & Fittings leftover from a 4-villa residential plumbing project. Includes SWR rubber-ring socketed grey drainage pipes (75mm & 110mm) + Single Y (45°) and Sanitary Tee (90°) junctions, UPVC Schedule 40 cold water supply lines, CPVC hot/cold plumbing lines, brass-insert threaded male/female transition elbows, brass ball valves (Red & Blue handle quarter-turn shutoffs), union couplers, step reducers, and 90°/45° bends. All items are brand new, sealed, and boxed. Ready for local site pickup.",
    category: "Pipes & Plumbing",
    condition: "Brand New / Surplus",
    quantity: 65,
    unit: "Pieces",
    price: 65,
    originalPrice: 120,
    location: "Peenya Industrial Area, Bengaluru",
    country: "India",
    contactPhone: "+91 97401 22334",
    contactEmail: "nikolas.surplus@blrbulders.in",
    image: {
      filename: "nikolas_cpvc_upvc_fittings_lot",
      url: "https://res.cloudinary.com/d6s3l2i7/image/upload/v1787637528/rebuildx_materials/nikolas_cpvc_upvc_fittings_lot.jpg",
    },
  },
  {
    title: "Aizar Self-Socketed Rigid White PVC Plumbing & Conduit Pipes (25mm to 50mm)",
    description:
      "High-grade virgin resin Aizar self-socketed bell-end white PVC pipes (assorted bundle in 20mm, 25mm, 32mm, and 40mm). Designed with integrated socket ends for quick solvent cement push-fit joints eliminating the need for extra couplers. Surplus inventory from a luxury resort development. Flame retardant, high tensile dielectric strength, UV protected, and zero lead formulation for safe water and electrical passage.",
    category: "Pipes & Plumbing",
    condition: "Brand New / Surplus",
    quantity: 160,
    unit: "Meters",
    price: 55,
    originalPrice: 95,
    location: "Kakkanad Industrial Park, Kochi",
    country: "India",
    contactPhone: "+91 94470 33221",
    contactEmail: "aizar.surplus@keralaconstructions.com",
    image: {
      filename: "aizar_white_socketed_pvc_pipes",
      url: "https://res.cloudinary.com/d6s3l2i7/image/upload/v1787637553/rebuildx_materials/aizar_white_socketed_pvc_pipes.jpg",
    },
  },
  {
    title: "Heavy Blue uPVC High-Pressure Drinking Water & Irrigation Delivery Pipes (63mm / 90mm)",
    description:
      "Unused surplus lot of PN-10 / PN-16 rated blue potable water pressure pipes. Leftover from municipal drinking water distribution extension project. High hoop strength, UV-stabilized, mirror-smooth hydraulic flow finish. Bundle contains standard 6-meter lengths (approx. 30 lengths = 180 meters) plus large diameter main feeder pipe section. Suitable for underground main water line, borewell delivery, or high-pressure agricultural irrigation.",
    category: "Pipes & Plumbing",
    condition: "Brand New / Surplus",
    quantity: 180,
    unit: "Meters",
    price: 160,
    originalPrice: 280,
    location: "GIDC Industrial Estate, Vadodara",
    country: "India",
    contactPhone: "+91 98980 66554",
    contactEmail: "gujarat.waterlines@gmail.com",
    image: {
      filename: "blue_hdpe_water_pressure_pipes",
      url: "https://res.cloudinary.com/d6s3l2i7/image/upload/v1787637552/rebuildx_materials/blue_hdpe_water_pressure_pipes.jpg",
    },
  },
  {
    title: "Handcrafted Solid CP Teak Wood Door Frames (4 Units)",
    description:
      "Seasoned Central Province (CP) solid teak wood door frames with routed rebate and sanded finish. Dimensions: 7ft x 3.5ft x 5in. Surplus custom millwork from luxury bungalow construction.",
    category: "Doors & Windows",
    condition: "Brand New / Surplus",
    quantity: 4,
    unit: "Pieces",
    price: 4800,
    originalPrice: 8500,
    location: "Thaltej, Ahmedabad",
    country: "India",
    contactPhone: "+91 98790 44332",
    contactEmail: "ahmedabadmillwork@gmail.com",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80",
    },
  },
  {
    title: "Asian Paints Royale Luxury Interior Matte Emulsion (4 x 20L Buckets)",
    description:
      "Unopened factory-sealed 20-litre cans of Asian Paints Royale luxury interior emulsion (Brilliant White). Teflon surface protector, wash-resistant, anti-bacterial formulation with low VOC. Remaining stock from a luxury duplex painting contract.",
    category: "Paints & Finishes",
    condition: "Brand New / Surplus",
    quantity: 80,
    unit: "Liters",
    price: 230,
    originalPrice: 340,
    location: "Banjara Hills, Hyderabad",
    country: "India",
    contactPhone: "+91 99890 12890",
    contactEmail: "hyd.decorpaints@gmail.com",
    image: {
      filename: "asian_paints_royale_lot",
      url: "https://asset7.ckassets.com/blog/wp-content/uploads/sites/5/2022/08/Paint-Brands.jpg",
    },
  },
  {
    title: "Berger WeatherCoat Long Life Exterior Silicon Emulsion (5 x 20L Buckets)",
    description:
      "Sealed 20-litre containers of Berger WeatherCoat Long Life 10 exterior architectural wall paint. PU & silicon-reinforced formula offering 10-year weather protection, anti-algal, and dust-resistant finish. Surplus from commercial facade project.",
    category: "Paints & Finishes",
    condition: "Brand New / Surplus",
    quantity: 100,
    unit: "Liters",
    price: 210,
    originalPrice: 320,
    location: "Whitefield, Bengaluru",
    country: "India",
    contactPhone: "+91 97401 55667",
    contactEmail: "blr.exteriorcoatings@gmail.com",
    image: {
      filename: "berger_weathercoat_buckets",
      url: "https://static.startuptalky.com/2025/05/Paints-Brands-India-StartupTalky-1.jpg",
    },
  },
  {
    title: "Heavy-Duty Exterior Acrylic Alkali-Resistant Wall Primer (6 x 20L Drums)",
    description:
      "Unopened 20L drums of deep-penetrating water-thinnable exterior wall primer. Binds porous cement plaster, provides superior topcoat adhesion, and seals against efflorescence. Unused inventory from a hospital project.",
    category: "Paints & Finishes",
    condition: "Brand New / Surplus",
    quantity: 120,
    unit: "Liters",
    price: 95,
    originalPrice: 145,
    location: "Manesar Industrial Area, Gurugram",
    country: "India",
    contactPhone: "+91 99100 88990",
    contactEmail: "ncr.primersurplus@gmail.com",
    image: {
      filename: "acrylic_wall_primer",
      url: "https://www.abcgroupindia.com/images/Paints.jpg",
    },
  },
  {
    title: "Machcoat High-Gloss Polyurethane Anti-Corrosion Industrial Metal Enamel (20L Drum)",
    description:
      "Surplus 20L drums of Machcoat heavy-duty polyurethane enamel finish for structural steel, GI metal sheds, gates, and industrial machinery. Outstanding chemical, moisture, and UV resistance with high gloss retention.",
    category: "Paints & Finishes",
    condition: "Brand New / Surplus",
    quantity: 3,
    unit: "Pieces",
    price: 3400,
    originalPrice: 5200,
    location: "Bhosari MIDC, Pune",
    country: "India",
    contactPhone: "+91 98220 77443",
    contactEmail: "pune.industrialcoatings@gmail.com",
    image: {
      filename: "machcoat_pu_metal_enamel",
      url: "https://antiquepaints.com/wp-content/uploads/2025/08/Machcoat-Product.png",
    },
  },
  {
    title: "Premium Designer Satin Interior Washable Paint (6 Cans x 4 Liters)",
    description:
      "Sealed 4-litre cans of premium designer architectural satin wall paint (Warm Alabaster White). 100% acrylic washable formula, stain-resistant, zero-odor low-VOC certification. Perfect for bedrooms, living rooms, and boutique interiors.",
    category: "Paints & Finishes",
    condition: "Brand New / Surplus",
    quantity: 6,
    unit: "Pieces",
    price: 1250,
    originalPrice: 1950,
    location: "Bandra West, Mumbai",
    country: "India",
    contactPhone: "+91 98200 44332",
    contactEmail: "mumbai.designerfinishes@gmail.com",
    image: {
      filename: "designer_satin_paint",
      url: "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1576010833-035777847213.jpg?crop=0.800xw:1xh;center,top&resize=980:*",
    },
  },
  {
    title: "Schneider Electric & Legrand 3-Phase MCB Breakers & Din-Rail Switchgear Lot",
    description:
      "Surplus lot of C-curve 10kA miniature circuit breakers (16A, 25A, 32A, 40A single-pole and triple-pole MCBs + 63A 4-pole isolators). Factory boxed, genuine Schneider Acti9 and Legrand RX3 series leftover from IT park panel assembly.",
    category: "Electrical",
    condition: "Brand New / Surplus",
    quantity: 24,
    unit: "Pieces",
    price: 185,
    originalPrice: 340,
    location: "Manesar Industrial Hub, Gurugram",
    country: "India",
    contactPhone: "+91 99100 22334",
    contactEmail: "ncr.switchgear@gmail.com",
    image: {
      filename: "mcb_switchgear_lot",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0RENnSBNaVI7WlbT9DdPu0Bam0Y2Mt7d7Au9HVKWpEGD9jRZhZ2Qth7nt&s=10",
    },
  },
  {
    title: "Heavy PVC Electrical Conduit Junction Boxes, Bends & Couplers Kit (150 Pcs)",
    description:
      "Complete surplus box containing 150 pieces of heavy gauge PVC conduit accessories: 1-way, 2-way, 3-way, and 4-way circular ceiling junction boxes with inspection lids, 20mm & 25mm deep bends, space saddles, and push-fit couplers. Unused remaining inventory from a hotel wiring contract.",
    category: "Electrical",
    condition: "Brand New / Surplus",
    quantity: 150,
    unit: "Pieces",
    price: 12,
    originalPrice: 24,
    location: "Kothrud Industrial Area, Pune",
    country: "India",
    contactPhone: "+91 98220 11445",
    contactEmail: "pune.electricsurplus@gmail.com",
    image: {
      filename: "pvc_conduit_fitting_kit",
      url: "https://5.imimg.com/data5/SELLER/Default/2021/6/WN/MC/IL/1656362/pvc-conduit-fitting-500x500.PNG",
    },
  },
  {
    title: "Anchor Roma & Havells 10A/16A Modular Switches, Sockets & Glass Faceplates Lot",
    description:
      "Unopened cartons of premium modular electrical fittings: 10A 1-way & 2-way rocker switches, 6A/16A universal shuttered sockets, fan step regulators, and 6M/8M pure white acrylic cover plates. Surplus stock from luxury apartment fit-outs.",
    category: "Electrical",
    condition: "Brand New / Surplus",
    quantity: 85,
    unit: "Pieces",
    price: 45,
    originalPrice: 85,
    location: "Whitefield, Bengaluru",
    country: "India",
    contactPhone: "+91 97401 77665",
    contactEmail: "blr.modularswitches@gmail.com",
    image: {
      filename: "modular_switches_sockets",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRCdoFXNbJKhhZRMcA2AHgIlpCNsCDIKByZw7U0LADWIYU04oDVUOUFaA&s=10",
    },
  },
  {
    title: "12-Way Double-Door Weatherproof IP65 Power Distribution Board Enclosure",
    description:
      "Heavy CRCA sheet metal powder-coated (RAL 7035) 12-way double door MCB distribution enclosure with integrated copper busbars, neutral links, and earthing terminal block. Ingress protection IP65 rated for indoor/outdoor installations.",
    category: "Electrical",
    condition: "Brand New / Surplus",
    quantity: 4,
    unit: "Pieces",
    price: 1850,
    originalPrice: 3400,
    location: "Sanand GIDC, Ahmedabad",
    country: "India",
    contactPhone: "+91 98790 33221",
    contactEmail: "ahmedabad.panels@gmail.com",
    image: {
      filename: "distribution_board_enclosure",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHSbp3pmKom6wdhjB2FGPZFjiljX3tZtMweVdKg-mMy5nY5KFcsBCJErL3&s=10",
    },
  },
  {
    title: "Polycab & Finolex 1.5 & 2.5 sq mm FR Pure Copper House Wire Coils (90m)",
    description:
      "100% pure electrolytic grade copper stranded flexible house wiring coils (90-meter sealed retail boxes). Assorted pack includes Red (Phase), Black (Neutral), Green (Earth), and Blue wires. Flame retardant (FR) PVC insulation with ISI certification.",
    category: "Electrical",
    condition: "Brand New / Surplus",
    quantity: 8,
    unit: "Pieces",
    price: 1350,
    originalPrice: 2150,
    location: "Sector 62, Noida",
    country: "India",
    contactPhone: "+91 98110 55667",
    contactEmail: "ncr.wirecables@gmail.com",
    image: {
      filename: "copper_house_wire_coils",
      url: "https://tiimg.tistatic.com/fp/1/007/776/multi-color-flexible-polyvinyl-chloride-electrical-wire-for-home-electrical-fitting-190.jpg",
    },
  },
  {
    title: "Galvanized Steel (GI) Concealed Modular Switch Back Boxes (100 Pcs Assorted)",
    description:
      "Heavy-duty 18-gauge hot-dip galvanized steel flush modular back boxes with brass earth screw and conduit knockouts. Assorted mix of 2-Module, 4-Module, 6-Module, and 8-Module sizes. Completely rust-proof for concrete wall casting.",
    category: "Electrical",
    condition: "Brand New / Surplus",
    quantity: 100,
    unit: "Pieces",
    price: 28,
    originalPrice: 55,
    location: "Peenya Industrial Area, Bengaluru",
    country: "India",
    contactPhone: "+91 97401 44332",
    contactEmail: "blr.electricalboxes@gmail.com",
    image: {
      filename: "gi_modular_metal_boxes",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTp2H1uP7s1AVS9Xgb9ZwBeHRmu-qIKtykB1Uyif5hel0mq9cwCQKcPcWO4&s=10",
    },
  },
  {
    title: "Greenply 19mm Marine Grade Waterproof Plywood (15 Sheets)",
    description:
      "IS:710 certified Greenply 19mm BWP (Boiling Water Proof) marine plywood full 8ft x 4ft sheets. Calibrated core, borer and termite proof. Ideal for modular kitchens and bathroom vanities.",
    category: "Wood & Timber",
    condition: "Brand New / Surplus",
    quantity: 15,
    unit: "Pieces",
    price: 2100,
    originalPrice: 3200,
    location: "Salt Lake, Kolkata",
    country: "India",
    contactPhone: "+91 98300 77665",
    contactEmail: "kolkatawoodworks@gmail.com",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1000&q=80",
    },
  },
  {
    title: "Italian Botticino Marble Slabs & Polished Cut Pieces",
    description:
      "Salvaged unused slabs and cut-to-size pieces of authentic Italian Botticino Beige marble (18mm thickness). High polish, fine grain, approx. 180 sq. ft. total. Excellent for fireplace surrounds, vanity tops, or accent flooring.",
    category: "Tiles & Marble",
    condition: "Gently Used / Salvaged",
    quantity: 180,
    unit: "Sq. Ft.",
    price: 140,
    originalPrice: 280,
    location: "Indiranagar, Bengaluru",
    country: "India",
    contactPhone: "+91 98450 33445",
    contactEmail: "stoneworks.bangalore@gmail.com",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80",
    },
  },
  {
    title: "Aluminum 3-Track Sliding Windows with Mosquito Mesh (5 Units)",
    description:
      "Jindal heavy aluminum powder-coated anodized bronze finish 3-track sliding window frames with 5mm toughened Saint-Gobain clear glass and SS-304 insect mesh. Standard size: 5ft (W) x 4ft (H).",
    category: "Doors & Windows",
    condition: "Like New / Unused",
    quantity: 5,
    unit: "Units",
    price: 3800,
    originalPrice: 6200,
    location: "Vashi, Navi Mumbai",
    country: "India",
    contactPhone: "+91 98200 44556",
    contactEmail: "navimumbaiglazing@gmail.com",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?auto=format&fit=crop&w=1000&q=80",
    },
  },
  {
    title: "AAC Lightweight Concrete Autoclaved Blocks (400 Blocks)",
    description:
      "Eco-friendly, thermal insulating AAC blocks (size: 600mm x 200mm x 150mm). Leftover order from green building certified commercial warehouse construction. Dry stacked.",
    category: "Bricks & Blocks",
    condition: "Brand New / Surplus",
    quantity: 400,
    unit: "Pieces",
    price: 55,
    originalPrice: 85,
    location: "Sector 48, Gurgaon",
    country: "India",
    contactPhone: "+91 98100 66778",
    contactEmail: "greenbuilder.ncr@gmail.com",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1590069261209-f8e9b8642343?auto=format&fit=crop&w=1000&q=80",
    },
  },
];

module.exports = { data: sampleListings };